project_id = "ldxxexjhhwtacpmsfehe"

[functions.webhook-handler]
verify_jwt = false

[functions.process-scheduled-automations]
verify_jwt = false

[functions.email-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false